[versions]
    jimmer = "0.9.119"
    springDependency = "1.1.7"
    springboot = "3.5.6"

[libraries]
    jimmer-spring-boot-starter = { module = "org.babyfish.jimmer:jimmer-spring-boot-starter", version.ref = "jimmer" }
    spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
    jimmer-apt = { module = "org.babyfish.jimmer:jimmer-apt", version.ref = "jimmer" }

[plugins]
    spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependency" }
    spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }
